// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHkHalEA1A4wSAlxQ-5u2c2ZNBJKKmoW0',
    appId: '1:581658724748:web:15cffe9a619b7b8617eea9',
    messagingSenderId: '581658724748',
    projectId: 'doctor-94e09',
    authDomain: 'doctor-94e09.firebaseapp.com',
    storageBucket: 'doctor-94e09.appspot.com',
    measurementId: 'G-24V28ZN50G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkO3b2AlZr-fk4Y1wqK8IoFPU9bLdCwjc',
    appId: '1:581658724748:android:820db9176b72c88017eea9',
    messagingSenderId: '581658724748',
    projectId: 'doctor-94e09',
    storageBucket: 'doctor-94e09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALN6K52e3e1jLsWakOcp-bTj54BXAvudM',
    appId: '1:581658724748:ios:319a2995a7abe9a417eea9',
    messagingSenderId: '581658724748',
    projectId: 'doctor-94e09',
    storageBucket: 'doctor-94e09.appspot.com',
    iosBundleId: 'com.doctor.pt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALN6K52e3e1jLsWakOcp-bTj54BXAvudM',
    appId: '1:581658724748:ios:d173e9883a72067b17eea9',
    messagingSenderId: '581658724748',
    projectId: 'doctor-94e09',
    storageBucket: 'doctor-94e09.appspot.com',
    iosBundleId: 'com.doctor.pt.RunnerTests',
  );
}
